
---
apiVersion: v1
kind: Service
metadata:
  name: pathnex-db
spec:
  clusterIP: None
  selector:
    app: pathnex-db
  ports:
    - port: 3306
      targetPort: 3306
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: pathnex-db
spec:
  serviceName: pathnex-db
  replicas: 3
  selector:
    matchLabels:
      app: pathnex-db
  template:
    metadata:
      labels:
        app: pathnex-db
    spec:
      containers:
        - name: db
          image: mysql:5.7
          ports:
            - containerPort: 3306
          env:
            - name: MYSQL_ROOT_PASSWORD
              value: "ChangeMeForPracticeOnly"
          volumeMounts:
            - name: mysql-storage
              mountPath: /var/lib/mysql
  volumeClaimTemplates:
    - metadata:
        name: mysql-storage
      spec:
        accessModes:
          - ReadWriteOnce
        resources:
          requests:
            storage: 1Gi
