
pipeline {
    agent any

    environment {
        IMAGE_NAME = 'pathnex-web-app'
        DOCKERHUB_USER = 'your-dockerhub-username'
    }

    stages {
        stage('Build Docker Image') {
            steps {
                script {
                    docker.build("${env.DOCKERHUB_USER}/${env.IMAGE_NAME}:latest")
                }
            }
        }

        stage('Push Docker Image') {
            steps {
                script {
                    docker.withRegistry('https://index.docker.io/v1/', 'docker-credentials') {
                        docker.image("${env.DOCKERHUB_USER}/${env.IMAGE_NAME}:latest").push()
                    }
                }
            }
        }

        stage('Deploy to Kubernetes') {
            steps {
                sh 'kubectl apply -f coding-practice/Day10/kubernetes/statefulset.yaml'
            }
        }
    }
}
