
stages:
  - build
  - push
  - deploy

variables:
  IMAGE_NAME: "$CI_REGISTRY_IMAGE/pathnex-web-app:$CI_COMMIT_SHORT_SHA"

build:
  stage: build
  script:
    - docker build -t "$IMAGE_NAME" .

push:
  stage: push
  script:
    - docker login "$CI_REGISTRY" -u "$CI_REGISTRY_USER" --password-stdin <<< "$CI_REGISTRY_PASSWORD"
    - docker push "$IMAGE_NAME"

deploy:
  stage: deploy
  script:
    - kubectl apply -f coding-practice/Day10/kubernetes/statefulset.yaml
